#!/usr/bin/env python
#--
# Simple script to list the git repos you have access to if using gitolite  
# -
import  sys, os
from subprocess import PIPE, Popen

# set this, or set ENV{'listrepos_repo'}
connect_string = ''  # something like git@yourserver.com

if '__main__' == __name__:
    if os.getenv("listrepos_repo"): cs = os.getenv("listrepos_repo")
    else: cs = connect_string
    
    stream = Popen(['ssh', '-T',  cs], stdin=PIPE, stdout=PIPE)
    rsp = stream.stdout.read().decode('utf-8')
    print(rsp)
